# Generated by Django 2.0.7 on 2018-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180902_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_model',
            name='attend_time',
        ),
        migrations.RemoveField(
            model_name='attendance_model',
            name='go_home',
        ),
        migrations.AddField(
            model_name='attendance_model',
            name='arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance_model',
            name='check_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
